workflows:
  build-dev-branch:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.md'
      - 'ai/**'
      - 'clients/python/**'
      - 'ui/**'
      - 'examples/**'
      - 'integration-tests/**'
      - 'tests/**'
