apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: unitycatalog-monorepo
  description: Unity Catalog monorepo component locations
spec:
  type: url
  targets:
    - ./server/catalog-info.yaml
    - ./ui/catalog-info.yaml
    - ./clients/java/catalog-info.yaml
    - ./connectors/spark/catalog-info.yaml
    - ./target/control/java/catalog-info.yaml
    - ./connectors/hadoop/catalog-info.yaml
