apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: unitycatalog-client
  title: Unity Catalog Java Client
  description: Java client library for the Unity Catalog REST API (cloud.celonis:unitycatalog-client).
  tags:
    - java
    - library
    - unitycatalog
  annotations:
    github.com/project-slug: celonis/unitycatalog
    sonarqube.org/project-key: celonis_unitycatalog_client
    repo-depot.celonis.dev/project-type: JAVA_MAVEN_CUSTOM
    repo-depot.celonis.dev/dply-release-approval-team: Storium
    repo-depot.celonis.dev/workflow-runner-release: runner=2cpu-linux-x64
spec:
  type: library
  lifecycle: experimental
  owner: storium
