name: '[RepoDepot] Run E2E Tests'
run-name: >-
  Running e2e tests on `${{ inputs.destination }}` (revision `${{ inputs.image-tag }}`) for `${{ inputs.component-name }}`

on:
  workflow_dispatch:
    inputs:
      component-name:
        type: choice
        description: Component Name
        required: true
        options:
          - unity-catalog-server
          - unitycatalog-client
          - unitycatalog-controlapi
          - unitycatalog-hadoop
          - unitycatalog-spark
      image-tag:
        description: ECR Image Tag (e.g. 20250113-152710_RC00)
        type: string
        required: true
      destination:
        type: string
        description: >-
          cfg destination the tests execute against, formatted as
          `{clusterName}--{namespace}` (e.g. `develop-main-c059b72--develop`).
        required: true
      stage:
        type: choice
        description: >-
          Kargo promotion stage. Filters test suites by their `type` field.
        required: true
        options:
          - develop
          - staging

jobs:
  run:
    name: Run E2E Tests
    uses: celonis/repo-depot/.github/workflows/reusable-run-e2e-tests.yaml@stable
    secrets: inherit
    with:
      component-name: ${{ inputs.component-name }}
      image-tag: ${{ inputs.image-tag }}
      destination: ${{ inputs.destination }}
      stage: ${{ inputs.stage }}
      repo-depot-version: stable
