name: '[RepoDepot] Hotfix Release Branch'
run-name: "${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/hotfix-release') && github.event.comment.body || 'Hotfix Release Branch No-Op' }}"

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  run:
    name: Run
    # Only run when triggered by a PR comment starting with `/hotfix-release`
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/hotfix-release')
    uses: celonis/repo-depot/.github/workflows/reusable-hotfix-release-branch.yaml@stable
    secrets: inherit
    with:
      pr-number: ${{ github.event.issue.number }}
      pr-hotfix-comment-id: ${{ github.event.comment.id }}
      pr-hotfix-command: ${{ github.event.comment.body }}
      repo-depot-version: stable
